import { Navbar } from "@/components/ui/navbar";
import { LandingHero } from "@/components/ui/landing-hero";
import { PathSelection } from "@/components/ui/path-selection";
import { useNavigate } from "react-router-dom";

export default function Landing() {
  const navigate = useNavigate();

  const handleSelectPath = (path: 'technical' | 'non-technical' | 'assessment') => {
    // Store the selected path and redirect to registration
    localStorage.setItem('selectedPath', path);
    navigate('/register');
  };

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <LandingHero />
      <PathSelection onSelectPath={handleSelectPath} />
      
      {/* Features Section */}
      <section id="features" className="py-24 px-4 sm:px-6 lg:px-8 bg-muted/30">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
              Everything You Need to Launch Your Startup
            </h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              From idea validation to market entry, our platform provides comprehensive guidance for student entrepreneurs.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {[
              {
                title: "AI-Powered Roadmaps",
                description: "Get personalized startup roadmaps generated by advanced AI based on your business idea and industry.",
                icon: "🤖"
              },
              {
                title: "Expert Mentorship",
                description: "Connect with experienced entrepreneurs and industry professionals who can guide your journey.",
                icon: "👨‍🏫"
              },
              {
                title: "Peer Community",
                description: "Build relationships with fellow student entrepreneurs and collaborate on exciting projects.",
                icon: "🤝"
              },
              {
                title: "Market Research",
                description: "Access tools and resources to validate your ideas and understand your target market.",
                icon: "📊"
              },
              {
                title: "Skill Development",
                description: "Learn essential entrepreneurial skills through interactive courses and practical exercises.",
                icon: "📚"
              },
              {
                title: "Progress Tracking",
                description: "Monitor your entrepreneurial journey with detailed analytics and milestone tracking.",
                icon: "📈"
              }
            ].map((feature, index) => (
              <div key={index} className="bg-card rounded-lg p-6 border border-border/50 hover:shadow-primary transition-all">
                <div className="text-4xl mb-4">{feature.icon}</div>
                <h3 className="text-xl font-semibold text-foreground mb-2">{feature.title}</h3>
                <p className="text-muted-foreground">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
            Ready to Start Your Entrepreneurial Journey?
          </h2>
          <p className="text-xl text-muted-foreground mb-8">
            Join thousands of students who are already building their dream startups with our platform.
          </p>
          <button 
            onClick={() => navigate('/register')}
            className="bg-gradient-primary text-primary-foreground hover:shadow-elegant hover:scale-105 transition-all font-semibold inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-lg ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 h-11 px-8 py-4"
          >
            Get Started Free
          </button>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-muted/50 py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <div className="w-8 h-8 bg-gradient-primary rounded-lg flex items-center justify-center">
              <span className="text-white font-bold">S</span>
            </div>
            <span className="text-xl font-bold">StartupLearn</span>
          </div>
          <p className="text-muted-foreground">
            Empowering the next generation of entrepreneurs
          </p>
        </div>
      </footer>
    </div>
  );
}